  
version: "3.3"

networks:
  redisApp:
    name: redisApp

services:
  redis:
    container_name: redis
    image: redis
    networks: 
      - redisApp
    ports:
      - 6379:6379
    volumes:
      - ./data/db:/data/db
  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs:alpine
    ports:
      - 8080:8080
    networks:
      - redisApp
    volumes:
      - ./:/app
    environment:
      PORT: 5000
      REDIS_PORT: 6379
    command: ["sh", "-c", "ls && npm i && npm start"]